import 'dart:async';

import 'package:bintango_indonesian_dictionary/feature/home/repository/translate_repository.dart';
import 'package:bintango_indonesian_dictionary/feature/home/state/translate_state.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'translate_provider.g.dart';

//Generated by @riverpod
// final homeNotifierProvider =
//     NotifierProvider<HomeNotifier, HomeState>(HomeNotifier.new);

@riverpod
class TranslateNotifier extends _$TranslateNotifier {
  @override
  TranslateState build() {
    return TranslateState();
  }

  late final _translateProvider = ref.read(translateRepositoryProvider);

  Future<void> updateInputText(String text) async {
    state.inputtedText = text;
    state = state.copyWith();
  }

  Future<void> searchWithWord(String text) async {
    state.inputtedText = text;
    state = state.copyWith();
    await searchWord();
  }

  Future<void> searchWord() async {
    if (state.inputtedText.length <= 1) {
      return;
    }
    state.isLoading = true;
    state = state.copyWith();
    final response = await _translateProvider.searchWord(state.inputtedText,);
    if (response != null) {
      state.searchedWord = response;
      unawaited(searchRelatedWords());
    } else {
      state
        ..searchedWord = null
        ..relatedWords = [];
    }
    state.isLoading = false;
    state = state.copyWith();
  }

  Future<void> getDetailExplanation() async {
    // state.isLoadingGrammarExplanation = true;
    // state = state.copyWith();
    // if (state.translateResponse != null && state.translateResponse!.text.isNotEmpty) {
    //   final response = await _translateProvider.getDetailExplanation(
    //       text: state.isLanguageSourceJapanese
    //           ? state.translateResponse!.text : state.inputtedText,
    //       isSourceJapanese: state.isLanguageSourceJapanese,);
    //   state
    //     ..getDetailExplanationResponse = response
    //     ..isLoadingGrammarExplanation = false;
    //   state = state.copyWith();
    // }
  }

  Future<void> searchRelatedWords() async {
    if (state.searchedWord != null && state.searchedWord?.description != null
        && state.searchedWord!.description!.isNotEmpty) {
      state.isLoadingWordList = true;
      state = state.copyWith();
      final relatedWordList =
      await _translateProvider.searchRelatedWords(state.searchedWord!);
      state
        ..relatedWords = relatedWordList
        ..isLoadingWordList = false;
      state = state.copyWith();
    }
  }
}
